FROM python:3.14.6-slim-trixie

RUN apt-get update && apt-get install -y \
    iptables \
    iproute2 \
    ca-certificates \
    gosu \
    expect \
    procps \
    jq \
    && pip install mitmproxy \
    && rm -rf /var/lib/apt/lists/*

RUN useradd -m mitmproxy

USER mitmproxy
WORKDIR /home/mitmproxy
RUN timeout 3s mitmweb || [ $? -eq 124 ]

USER root
# Set up entrypoint script
COPY pi-coding-agent-proxy/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

EXPOSE 8080 8081

ENTRYPOINT ["/entrypoint.sh"]