repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: uv run --project . ruff check --fix
        language: system
        types: [python]
        pass_filenames: false
        always_run: false

      - id: ruff-format
        name: ruff-format
        entry: uv run --project . ruff format --check
        language: system
        types: [python]
        pass_filenames: false
        always_run: false

      - id: pytest
        name: pytest
        entry: uv run --project . pytest
        language: system
        types: [python]
        pass_filenames: false


